version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grace-hub
    ports:
      - "3000:3000"
    env_file:
      - .env  # Las variables REALES se cargan aquí
    environment:
      - NODE_ENV=production
    restart: unless-stopped